[package]
name = "rust-chip8-emulator"
version = "0.1.0"
authors = ["Julian Ollivieira <julian.ollivieira@gmail.com>"]
edition = "2021"
description = "ğŸ•¹ï¸ A CHIP-8 interpreter written in Rust using Rust-SDL2"
readme = "README.md"
repository = "https://github.com/julianollivieira/rust-chip8-interpreter"
license = "MIT"
license-field = "LICENSE"

[dependencies]
sdl2 = "0.35"
rand = "0.8.0"